### ISSUE TITLE
UnknownHostException with docker-compose.allinone.hsql

### ISSUE THREAD

**Issue by bwulff** [learnweb/docker-opencast#1]
Tried docker-compose.allinone.hsql.yml on Mac using the command line from the README. 

OC was not able to register services at its service registry. Cause was an UnknownHostException saying 'Unknown host opencast'.

Changing the host to localhost:8080 in line 30 solved the issue for me.

I'm new to docker so maybe I just did not configure my machine right. Wanted to report though.

**Comment by JanKoppe** [comment]
Yes, you would need to change the hostname. Maybe it would be a good idea to make localhost the default. Let's see what @mtneug has to say about that. Should be done for all files then.

**Comment by mtneug** [comment]
Thank you for reporting @bwulff. As stated in the README the hostname in `ORG_OPENCASTPROJECT_SERVER_URL` should be changed to one that can be resolved:

> Before you start the system, you probably should change `ORG_OPENCASTPROJECT_SERVER_URL` to a proper hostname or IP address in `docker-compose/docker-compose.allinone.hsql.yml`.

Setting it to `localhost` by default is probably the best alternative which was done in #2. However if you run the Docker Engine in a virtual machine, for example with [`docker-machine`](https://github.com/docker/machine), `localhost` will not be correct. Currently this is necessary if you use Docker on Mac OS X or Windows. Adapting the hostname is thus still relevant.
